name: Default Pipeline
on: push
jobs:
  Analyzer:
    name: 'Run flutter analyzer'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
      - run: flutter pub get
      - run: flutter analyze
  Tests:
    name: 'Run flutter tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
      - run: flutter pub get
      - run: flutter test
  Build:
    name: 'Build APK'
    needs:
      - Analyzer
      - Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: 'Build web version'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
      - run: flutter build apk
