name: Default Pipeline
on: push
jobs:
  Analyzer:
    name: 'Run flutter analyzer'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
  Tests:
    name: 'Run flutter tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
  Build_Testing:
    environment: testing
    if: github.ref == 'refs/heads/testing'
    name: 'Build APK for Testing'
    needs:
      - Analyzer
      - Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: subosito/flutter-action@v2.10.0
      - name: 'Build Testing APK'
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
      - run: flutter build apk
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: testing-apk
          path: build/app/outputs/flutter-apk/app-release.apk
  Build_aab:
    environment: stable
    if: github.ref == 'refs/heads/stable'
    name: 'Build Signed AAB for Production'
    needs:
      - Analyzer
      - Tests
    runs-on: ubuntu-latest
    env:
      PROPERTIES_PATH: "./android/key.properties"
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: subosito/flutter-action@v2.10.0
      - name: 'Build Production AAB'
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
      - run: |
          echo keyPassword=\${{ secrets.KEY_PASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.KEY_STORE_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.ALIAS }} >> ${{env.PROPERTIES_PATH}}
          echo storeFile=\${{ secrets.STORE_FILE }} >> ${{env.PROPERTIES_PATH}}
      - run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/key.jks
      - run: flutter build appbundle
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release